In [1]:
import numpy as np

In [2]:
a = [10,28,39,30,38]
np.mean(a)

np.float64(29.0)

In [3]:
d1 = np.array([1,2,3,4,5])

In [4]:
d1

array([1, 2, 3, 4, 5])

In [5]:
d1.ndim

1

In [6]:
d2 = np.array([[1,2,3,4,5],[10,20,30,40,50]])

In [7]:
d2

array([[ 1,  2,  3,  4,  5],
       [10, 20, 30, 40, 50]])

In [9]:
d2.ndim

2

In [10]:
d3 = np.array([[[1,2,3],[10,20,30],[0.1,0.2,0.3]]])

In [11]:
d3

array([[[ 1. ,  2. ,  3. ],
        [10. , 20. , 30. ],
        [ 0.1,  0.2,  0.3]]])

In [12]:
d3.ndim

3

In [8]:
np.random.random_integers(1,10,5)

C:\Users\renuka\AppData\Local\Temp\ipykernel_13644\3200928123.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 10 + 1) instead
  np.random.random_integers(1,10,5)


array([2, 3, 1, 2, 8], dtype=int32)

In [9]:
np.std([10,20,30,45,64])

np.float64(19.019989484749985)

In [16]:
np.var([10,20,30,45,64])

np.float64(361.76)

In [17]:
np.median([10,20,30,45,64])

np.float64(30.0)

In [11]:
import statistics

In [12]:
data = [10,20,36,73,89,20,10,10,2,10]
statistics.mode(data)

10